---
version: 1

kind: experiment

environment:
  resources:
    cpu:
      requests: 1
      limits: 1
    gpu:
      requests: 1
      limits: 1

declarations:
  batch_size: 64
  learning_rate: 0.0001
  dropout: 0.25
  num_epochs: 20
  sample_size: 10000

run:
  image: tensorflow/tensorflow:1.8.0-gpu-py3
  build_steps:
    - pip3 install --no-cache-dir -U polyaxon-helper
    - pip3 install --no-cache-dir -U  keras
  env_vars:
    - ['LD_LIBRARY_PATH', '/usr/local/nvidia/lib64']
  cmd: python3 finefood/run.py --batch_size={{ batch_size }} \
                         --learning_rate={{ learning_rate }} \
                         --dropout={{ dropout }} \
                         --num_epochs={{ num_epochs }} \
                         --sample_size={{ sample_size }}

