apiVersion: v1
kind: PersistentVolume
metadata:
  name: polyaxon-pv-outputs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.128.0.6  # Use the right IP
    path: "/data/outputs"
  claimRef:
    namespace: polyaxon 
    name: polyaxon-pvc-outputs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: polyaxon-pvc-outputs 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
